1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [4]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = len(zp)
b1 = (n * np.sum(zp*ks) - np.sum(zp) * np.sum(ks))/(n * np.sum(zp**2) - np.sum(zp)**2)
b0 = np.mean(ks) - b1 * np.mean(zp)
y = b0 + b1 * zp
print(y)
print(b1)

[535.89621821 562.10160703 942.07974498 968.2851338  548.99891262
 627.61507909 585.68645697 837.25818968 758.64202321 732.43663439]
2.6205388824027653


2) Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [10]:
alpha = 0.000001
b1 = 0.1
n = len(zp)
for i in range(10):
  b1 -= alpha * (2/n) * np.sum((b1 * zp - ks) * zp)
  y = b1 * zp
  print(y)

[[ 52.92434 ]
 [ 68.04558 ]
 [287.30356 ]
 [302.4248  ]
 [ 60.48496 ]
 [105.84868 ]
 [ 81.654696]
 [226.8186  ]
 [181.45488 ]
 [166.33364 ]]
[[ 88.73069275]
 [114.08231925]
 [481.68090351]
 [507.03253001]
 [101.406506  ]
 [177.4613855 ]
 [136.8987831 ]
 [380.2743975 ]
 [304.219518  ]
 [278.8678915 ]]
[[114.67124952]
 [147.43446366]
 [622.5010688 ]
 [655.26428295]
 [131.05285659]
 [229.34249903]
 [176.9213564 ]
 [491.44821221]
 [393.15856977]
 [360.39535562]]
[[133.46435279]
 [171.59702502]
 [724.52077231]
 [762.65344454]
 [152.53068891]
 [266.92870559]
 [205.91643003]
 [571.9900834 ]
 [457.59206672]
 [419.4593945 ]]
[[147.07935474]
 [189.10202752]
 [798.43078288]
 [840.45345566]
 [168.09069113]
 [294.15870948]
 [226.92243303]
 [630.34009174]
 [504.2720734 ]
 [462.24940061]]
[[156.94298797]
 [201.78384168]
 [851.97622041]
 [896.81707411]
 [179.36341482]
 [313.88597594]
 [242.14061001]
 [672.61280559]
 [538.09024447]
 [493.24939076]]
[[164.08887461]
 [210.97141021]
 [890.76817645]
 [937.

3) Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).



In [5]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
zp = zp.reshape(-1,1)
regres = model.fit(zp,ks)
b0 = regres.intercept_
b1 = regres.coef_
y = b0 + b1 * zp
print(y)

[[535.89621821]
 [562.10160703]
 [942.07974498]
 [968.2851338 ]
 [548.99891262]
 [627.61507909]
 [585.68645697]
 [837.25818968]
 [758.64202321]
 [732.43663439]]
